# Generated by Django 5.2.8 on 2025-11-29 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_user_id', models.CharField(blank=True, editable=False, help_text='Auto Student System ID', max_length=20, null=True, unique=True)),
                ('admission_id', models.CharField(blank=True, editable=False, help_text='Auto generated admission ID', max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('roll_number', models.CharField(blank=True, help_text='Institute-wise roll or internal student code.', max_length=20, null=True)),
                ('registration_no', models.CharField(blank=True, help_text='Board/official registration no.', max_length=30, null=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_relation', models.CharField(blank=True, help_text='Father / Mother / Uncle etc.', max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='students/profile/')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='students/docs/')),
                ('id_card_no', models.CharField(blank=True, help_text='Internal ID card number.', max_length=30, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Leave', 'Leave'), ('Suspended', 'Suspended'), ('Passed Out', 'Passed Out')], db_index=True, default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.schoolclass')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.session')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Information',
                'verbose_name_plural': 'Students Information',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'class_name', 'section', 'roll_number'), name='unique_roll_per_class_section_session')],
            },
        ),
    ]
