# Generated by Django 5.2.8 on 2025-11-17 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user_id', models.IntegerField(blank=True, help_text='Auto-generated Admin ID (e.g., 250310001 → YYMM1XXXX)', null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('street', models.CharField(blank=True, help_text='Street address', max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, help_text='State / Province', max_length=100)),
                ('zip_code', models.CharField(blank=True, help_text='ZIP / Postal Code', max_length=20)),
                ('country', models.CharField(default='Bangladesh', help_text='Country', max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='admin_profiles/')),
                ('password', models.CharField(blank=True, help_text='Temporary field for registration.', max_length=128, null=True)),
                ('confirm_password', models.CharField(blank=True, help_text='Confirm password.', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
