# Generated by Django 5.2.8 on 2025-11-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Select gender', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
