# Generated by Django 5.2.8 on 2025-11-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='street',
        ),
    ]
